project_id = "hhfiawskggxnvffcpaxu"

[functions.admin-reset-password]
verify_jwt = false

[functions.submit-custom-quote]
verify_jwt = false

[functions.send-discord-notification]
verify_jwt = false

[functions.discord-bot-handler]
verify_jwt = false

[functions.test-discord-buttons]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.suggest-interlinking]
verify_jwt = false